### ISSUE TITLE
Problema com a autenticação do Facebook

### ISSUE THREAD

**Issue by gabrielhaase** [elisei/social-login#10]
Olá Bruno, boa tarde.
Estou utilizando este módulo em um projeto e encontrei um problema ao efetuar a criação da conta usando o Facebook.
A autenticação do usuário acontece com sucesso porém nas informações relativas ao usuário recebidas do Facebook o email está retornando vazio e desta forma o Magento não consegue criar o usuário e lança a mensagem de erro "Unable to login, try another way.".

Por acaso já vivenciou este problema. Consegue ajudar?

Grato,
Gabriel Haase

**Comment by elisei** [comment]
Oi @gabrielhaase 

Você precisa de 2 ações, uma em:
Análise do Aplicativo -> Permissões e recursos
https://developers.facebook.com/apps/825777625486363/app-review/permissions/

Pedir o acesso ao email e public_profile

Depois disso no topo mude o APP para produção (terá que completar algumas informações e o formulário).
