### ISSUE TITLE
Magento 2.4.4 PHP 8.1 - Optional parameter $customerSession declared before required parameter $accountRedirect 

### ISSUE THREAD

**Issue by redati** [elisei/social-login#11]
### Bug description
 Deprecated Functionality: Optional parameter $customerSession declared before required parameter $accountRedirect is implicitly treated as a required parameter in /var/www/html/vendor/o2ti/social-login/Provider/Provi  
  der.php on line 152  

?CustomerSession $customerSession = null,

parâmetros opcionais devem estar depois do obrigatórios, 

deixando assim, não explícito, mas mantendo a ordem, compilou normal.
  CustomerSession $customerSession = null,

#### Expected behaviour
Compilar Magento.

#### Actual behaviour
Error: 
 Deprecated Functionality: Optional parameter $customerSession declared before required parameter $accountRedirect is implicitly treated as a required parameter in /var/www/html/vendor/o2ti/social-login/Provider/Provi  
  der.php on line 152  

### How to reproduce
1 Atualiza magento 2.4.4  php8.1 
2 compila o codigo. 

### Your personal set up

```

```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by elisei** [comment]
@redati 

Confirmado, mas realmente não vou mexer nisso antes dessa quinzena (pelo menos).

Estou avisando apenas para que tente contornar por ai...

**Comment by redati** [comment]
Sim eu entendo, qualquer coisa deixarei anotado aqui ou no checkout, caso eu encontre problema e solução para a versão nova. Abraço.

**Comment by elisei** [comment]
@redati 

Nova versão já corrigindo! :D
