### ISSUE TITLE
Após configurar módulo não consigo logar (facebook)

### ISSUE THREAD

**Issue by mauricio-tonny** [elisei/social-login#12]
Instalado e configurado login via facebook, porém ao tentar efetuar o login recebo a seguinte mensagem:

![Captura de tela de 2022-04-25 08-23-08](https://user-images.githubusercontent.com/68695691/165081095-87f77356-1ecc-46bd-803a-b443c7a6b278.png)

Verifiquei o processo do zero e fiz a atualização do social login via terminal, o retorno foi:

Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading o2ti/social-login (101.1.5)
  - Upgrading o2ti/social-login (101.1.4 => 101.1.5): Extracting archive

Em contrapartida, recebi a seguinte mensagem de quem está me auxiliando no teste:

![erro_hybrid](https://user-images.githubusercontent.com/68695691/165081347-a16ac34d-be5d-4616-9998-156b94775a65.jpeg)

Tendo isso como parametro, notei que o erro poderia estar vinculado ao Hybrid, fiz a atualização do mesmo via terminal a recebi o seguinte retorno:

Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading hybridauth/hybridauth (v3.8.0)
  - Upgrading hybridauth/hybridauth (3.7.1 => v3.8.0): Extracting archive

Porém mesmo assim persiste o "problema" Existe algo que eu possa ter deixado passar?

Magento, versão:  Magento CLI 2.4.3-p1

**Comment by elisei** [comment]
Oi @mauricio-tonny,

Por favor defina a opção "Mostrar CPF/CNPJ" como não!
![image](https://user-images.githubusercontent.com/1786389/165088214-8ec075ed-2774-4803-8a6d-5b0e3f849cb1.png)

E então, tente novamente.

Se determina um atributo que não pode ser obtido dos logins sociais (CPF/CNPJ) o login social não irá funcionar para novos clientes!

Para validação de CPF recomendo ativar o vat_id (ele é um atributo de endereço) presente no checkout, você ainda pode usar o https://github.com/elisei/tax-document-validation-br para validar o CPF/CNPJ

**Comment by elisei** [comment]
@mauricio-tonny por falta de interação estou marcando o issue como resolvido, caso o problema perista reabra!
