### ISSUE TITLE
Redirecionamento após login

### ISSUE THREAD

**Issue by redati** [elisei/social-login#3]
Estou tentando implementar forma de direcionar para checkout, caso cliente esteja com itens no carrinho,  mas sem sucesso, o redirecionamento para autenticação padrão funciona com a extensão gustavoulyssea/magento-redirect-checkout que usa plugin para alterar o Url antes da autenticação:

public function afterLoadCustomerQuote(
        \Magento\Checkout\Model\Session $_subject,
        $result
    )
    {
        $_quote = $_subject->getQuote();
        if(count($_quote->getAllItems())>0){
            $this->_customerSession
                ->setBeforeAuthUrl($this->_storeManager->getStore()->getUrl('checkout'));
        }
    }

Porém para o login social não funciona,

**Comment by elisei** [comment]
Oi @redati tudo bem?

[Nessa linha](https://github.com/elisei/social-login/blob/master/Controller/Endpoint/Index.php#L52) é definido a url direcionamento com base na url que gerou a ação. 

Considero isso importante pois devolve o usuário para o ponto em que ele estava mas já autenticado, exemplo disso:
você quer fazer a avaliação do produto https://cristaisaquarius.com.br/xam-pontas-e-obeliscos-xam-650 usando o login social você é devolvido para cá...

Você pode implementar a sua logica de redirect aqui https://github.com/elisei/social-login/blob/381d4b3e311f47bdfb63586030d61efd614277e5/Provider/Provider.php#L324 onde pode sobrescrever o atual redir caso haja o getBeforeAuthUrl() na session do customer! =)

**Comment by redati** [comment]
Você é o cara, quando eu ficar bom nisso espero contribuir para seus módulos se possível, são ótimos.

Vou fazer a implementação.

Um contexto.

Guest Cart no magento 2 esta um problema, o recaptcha invisível do magento falha algumas vezes no checkout, pelo hotjar observei alguns poucos casos de pessoas que abandonou por não saber o que se tratava  e para um publico alvo de idade mais avançada é complicado colocar captcha manual, eu vi a taxa de conversão caindo muito.

Fui obrigado a pedido o cadastro andas do checkout, estou trabalhando para desenvolver algo para melhorar isso.

Sem recaptcha, acabai sofrendo um ataque bem avançado com muitas tentativas de cartão clonado, ips brasileiros e todos os detalhes das solicitações autênticas.  Essa inssue é antiga no magento e muita gente é afetada https://github.com/magento/magento2/issues/28614 

Abraços.

**Comment by elisei** [comment]
@redati 

Valeu =) 

umas dúvidas aproveitando o tópico... 
notei que meus amadinhos não sabiam que microsoft live é @yahoo @hotmail.... por isso troquei em meu projeto por continue com hotmail/yahoo... (aumentaram muitos os clicks nele, veja se não vale compensa fazar isso por ai).

sobre o recaptcha há uma config por la que pode tornar mais ou menos sensível a ser ou não um bot e pode sempre baixa o relatório para ficar de olho... talvez você ainda esteja sendo afetado por esse esquentador e por isso está mais sensivel a travar no invisível!

A minha ideia la para o checkout é sumir com email "visível" virar um botão para só entao poder digitar um email, a realidade é que clientes não lembram senha e só se complicam por usar esse meio.
