### ISSUE TITLE
Erro após atualizar magento para v2.4.2

### ISSUE THREAD

**Issue by adorobeleza** [elisei/social-login#4]
Após digitar a bin/magento setup:upgrade

O seguinte erro é exibido:

In ClassReader.php line 45:

Impossible to process constructor argument Parameter #0 [ <required> Hybridauth\HybridauthFactory $hybridauthFactory ] of O2TI\SocialLogin\Provider\Provider class

In ClassReader.php line 34:

Class Hybridauth\HybridauthFactory does not exist

**Comment by elisei** [comment]
Olá @adorobeleza 

O Hybridauth está [listado nas dependências](https://github.com/elisei/social-login/blob/master/composer.json#L10) do módulo. Por isso você deve fazer a instalação via composer.

**Comment by adorobeleza** [comment]
Deu certo, obrigado !
